name: Fx.TransMorph
author: cheeaun
category: Effects
tags: [effects, morph]
current: 0.2
docs: http://github.com/cheeaun/Fx.TransMorph/blob/master/Docs/Fx.TransMorph.md
demo: http://cheeaun.github.com/Fx.TransMorph